#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MotionsRace.Droid.Resource", IsApplication=true)]

namespace MotionsRace.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::MotionsRace.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::MotionsRace.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::MotionsRace.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::MotionsRace.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::MotionsRace.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::MotionsRace.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::MotionsRace.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::MotionsRace.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::MotionsRace.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::MotionsRace.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::MotionsRace.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::MotionsRace.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::MotionsRace.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::MotionsRace.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::MotionsRace.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::MotionsRace.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::MotionsRace.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::MotionsRace.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::MotionsRace.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::MotionsRace.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::MotionsRace.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::MotionsRace.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::MotionsRace.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::MotionsRace.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::MotionsRace.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::MotionsRace.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::MotionsRace.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::MotionsRace.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::MotionsRace.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::MotionsRace.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::MotionsRace.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::MotionsRace.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::MotionsRace.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::MotionsRace.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::MotionsRace.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::MotionsRace.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::MotionsRace.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::MotionsRace.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::MotionsRace.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::MotionsRace.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::MotionsRace.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::MotionsRace.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::MotionsRace.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::MotionsRace.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::MotionsRace.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::MotionsRace.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::MotionsRace.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::MotionsRace.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::MotionsRace.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::MotionsRace.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::MotionsRace.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::MotionsRace.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::MotionsRace.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::MotionsRace.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::MotionsRace.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::MotionsRace.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::MotionsRace.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::MotionsRace.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.String.ApplicationName = global::MotionsRace.Droid.Resource.String.ApplicationName;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.String.Hello = global::MotionsRace.Droid.Resource.String.Hello;
			global::Splat.Resource.String.library_name = global::MotionsRace.Droid.Resource.String.library_name;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::MotionsRace.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::MotionsRace.Droid.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int clock = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int move01 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int move02 = 2131034114;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarColor = 2130771978;
			
			// aapt resource value: 0x7f010012
			public const int ahBarLength = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int ahBarWidth = 2130771985;
			
			// aapt resource value: 0x7f01000f
			public const int ahCircleColor = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int ahDelayMillis = 2130771982;
			
			// aapt resource value: 0x7f010010
			public const int ahRadius = 2130771984;
			
			// aapt resource value: 0x7f01000b
			public const int ahRimColor = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int ahRimWidth = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int ahSpinSpeed = 2130771981;
			
			// aapt resource value: 0x7f010007
			public const int ahText = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int ahTextColor = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int ahTextSize = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int default_screen_bg = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int light_gray_header_color = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int rounded_container_bg = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int rounded_container_border = 2131230722;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int checkbox = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int checkbox_selected = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int checkbox_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int clock_animation_01 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int clock_animation_02 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int clock_animation_03 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int clock_animation_04 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int clock_animation_05 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int clock_animation_06 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int clock_animation_07 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int clock_animation_08 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int clock_animation_09 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int clock_animation_10 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int clock_animation_11 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int clock_animation_12 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int clock_icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int clock_icon_white = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int cloud_refresh = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int custom_background_splash = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int custom_body_main = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int custom_btn_main = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int custom_header_main = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int custom_progress_bar_horizontal_main = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int custom_scrollbar_thumbvertical_main = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int custom_scrollbar_trackvertical_main = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_errorstatus = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_lock = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_login = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_successstatus = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Icon = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int intensity2 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int intensity_1 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int intensity_2 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int intensity_3 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int intensity_4 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int intensity_5 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int intensity_bg_grey = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int intensity_bg_orange = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int intensity_circle = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int intensity_circle_black = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int intensity_circle_orange = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int intensity_empty = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int intensity_progress = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int LoginPassword = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int LoginUser = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int restart = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int roundedbg = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int roundedbgdark = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Screen = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int select_image = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int splashmotion = 2130837554;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int IntensityGridBlack = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int IntensityGridOrange = 2131165191;
			
			// aapt resource value: 0x7f070022
			public const int LinearLayoutHome = 2131165218;
			
			// aapt resource value: 0x7f070000
			public const int MvvmCrossTagId = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MvxBindingTagUnique = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int UiHeader = 2131165187;
			
			// aapt resource value: 0x7f070017
			public const int UiHsdfsdfsdf = 2131165207;
			
			// aapt resource value: 0x7f070042
			public const int appVersion = 2131165250;
			
			// aapt resource value: 0x7f070016
			public const int btnCancel = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int btnFinish = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int btnPauseResume = 2131165205;
			
			// aapt resource value: 0x7f07002f
			public const int btnTryToRefresh = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int btnTryToRestart = 2131165232;
			
			// aapt resource value: 0x7f070033
			public const int buttonRecordActivity = 2131165235;
			
			// aapt resource value: 0x7f070010
			public const int cancel = 2131165200;
			
			// aapt resource value: 0x7f070005
			public const int checkboxdates = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int checkboxescontainer = 2131165188;
			
			// aapt resource value: 0x7f070040
			public const int closeOAuthLink = 2131165248;
			
			// aapt resource value: 0x7f07003d
			public const int customButton = 2131165245;
			
			// aapt resource value: 0x7f070046
			public const int ellipse1 = 2131165254;
			
			// aapt resource value: 0x7f070047
			public const int ellipse2 = 2131165255;
			
			// aapt resource value: 0x7f070048
			public const int ellipse3 = 2131165256;
			
			// aapt resource value: 0x7f070019
			public const int feedImage = 2131165209;
			
			// aapt resource value: 0x7f07003e
			public const int forgotPassword = 2131165246;
			
			// aapt resource value: 0x7f070034
			public const int imageLayout = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int imageView1 = 2131165237;
			
			// aapt resource value: 0x7f07001f
			public const int imageViewHeder = 2131165215;
			
			// aapt resource value: 0x7f07000e
			public const int imageselected = 2131165198;
			
			// aapt resource value: 0x7f070008
			public const int intensity_slider = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int intensitytap1 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int intensitytap2 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int intensitytap3 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int intensitytap4 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int intensitytap5 = 2131165197;
			
			// aapt resource value: 0x7f070012
			public const int ivAnimateClock = 2131165202;
			
			// aapt resource value: 0x7f070039
			public const int layoutEmail = 2131165241;
			
			// aapt resource value: 0x7f070037
			public const int layoutHome = 2131165239;
			
			// aapt resource value: 0x7f07003f
			public const int layoutOauth = 2131165247;
			
			// aapt resource value: 0x7f07003b
			public const int layoutPassword = 2131165243;
			
			// aapt resource value: 0x7f07001e
			public const int leftPanel = 2131165214;
			
			// aapt resource value: 0x7f070024
			public const int linearLayout1 = 2131165220;
			
			// aapt resource value: 0x7f070026
			public const int linearLayout2 = 2131165222;
			
			// aapt resource value: 0x7f070023
			public const int linearLayout3 = 2131165219;
			
			// aapt resource value: 0x7f070018
			public const int list = 2131165208;
			
			// aapt resource value: 0x7f070013
			public const int llPauseFinish = 2131165203;
			
			// aapt resource value: 0x7f07001c
			public const int loadingImage = 2131165212;
			
			// aapt resource value: 0x7f07001a
			public const int loadingProgressBar = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int loadingProgressWheel = 2131165213;
			
			// aapt resource value: 0x7f070021
			public const int mainRoot = 2131165217;
			
			// aapt resource value: 0x7f070044
			public const int multiImageLayout = 2131165252;
			
			// aapt resource value: 0x7f070032
			public const int mvx_MvxListView2 = 2131165234;
			
			// aapt resource value: 0x7f070027
			public const int myactivities = 2131165223;
			
			// aapt resource value: 0x7f070041
			public const int oauthButton = 2131165249;
			
			// aapt resource value: 0x7f07002e
			public const int relativeLayout1 = 2131165230;
			
			// aapt resource value: 0x7f070020
			public const int rightPanel = 2131165216;
			
			// aapt resource value: 0x7f070029
			public const int rlDetailFeedInfo = 2131165225;
			
			// aapt resource value: 0x7f07000f
			public const int save = 2131165199;
			
			// aapt resource value: 0x7f070049
			public const int signIn = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int signUp = 2131165258;
			
			// aapt resource value: 0x7f070043
			public const int splashLayout = 2131165251;
			
			// aapt resource value: 0x7f07002a
			public const int svDetailFeedInfo = 2131165226;
			
			// aapt resource value: 0x7f070031
			public const int swipeRefreshLayout = 2131165233;
			
			// aapt resource value: 0x7f07003a
			public const int textEmail = 2131165242;
			
			// aapt resource value: 0x7f070036
			public const int textLayout = 2131165238;
			
			// aapt resource value: 0x7f07003c
			public const int textPassword = 2131165244;
			
			// aapt resource value: 0x7f070038
			public const int textTitle = 2131165240;
			
			// aapt resource value: 0x7f070002
			public const int textView1 = 2131165186;
			
			// aapt resource value: 0x7f07001b
			public const int textViewStatus = 2131165211;
			
			// aapt resource value: 0x7f070028
			public const int togglebutton = 2131165224;
			
			// aapt resource value: 0x7f07002b
			public const int tvDate = 2131165227;
			
			// aapt resource value: 0x7f07002d
			public const int tvFullMessage = 2131165229;
			
			// aapt resource value: 0x7f07002c
			public const int tvTitle = 2131165228;
			
			// aapt resource value: 0x7f070025
			public const int txtParticipantName = 2131165221;
			
			// aapt resource value: 0x7f070011
			public const int waitLayout = 2131165201;
			
			// aapt resource value: 0x7f070045
			public const int welcomGallery = 2131165253;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int ActivityCheckBoxItem = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ActivityItem = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ActivityItemView = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ActivityTypeItemsItem = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ActivityTypesItem = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ActivityTypesView = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int FixAdapterLinking = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int FrequentTrainingView = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ImageViewerView = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int loading = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int loadingimage = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int loadingprogress = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int MainHederFragment = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int MainItem = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int MainView = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int SignInView = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int SplashScreen = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int WelcomeView = 2130968593;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int app_name = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int library_name = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090005
			public const int CustomProgressBarMain = 2131296261;
			
			// aapt resource value: 0x7f090000
			public const int Theme_MainView = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int Theme_SignInView = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int Theme_Splash = 2131296258;
			
			// aapt resource value: 0x7f090006
			public const int Theme_WelcomeView = 2131296262;
			
			// aapt resource value: 0x7f090003
			public const int btnStyleSignIn = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int myPopupMenuStyle = 2131296260;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[]
			{
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[]
			{
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] ProgressWheel = new int[]
			{
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
