// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MotionsRace.Core {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MotionsRace.Core.Localize.en", typeof(en).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string GLOBAL_AppName {
            get {
                return ResourceManager.GetString("GLOBAL_AppName", resourceCulture);
            }
        }
        
        public static string GLOBAL_Error {
            get {
                return ResourceManager.GetString("GLOBAL_Error", resourceCulture);
            }
        }
        
        public static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        public static string Login_EmailRequired {
            get {
                return ResourceManager.GetString("Login_EmailRequired", resourceCulture);
            }
        }
        
        public static string Login_NoActiveRaces {
            get {
                return ResourceManager.GetString("Login_NoActiveRaces", resourceCulture);
            }
        }
        
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        public static string Login_PasswordRequired {
            get {
                return ResourceManager.GetString("Login_PasswordRequired", resourceCulture);
            }
        }
        
        public static string Login_SelectRace {
            get {
                return ResourceManager.GetString("Login_SelectRace", resourceCulture);
            }
        }
        
        public static string Login_SignIn {
            get {
                return ResourceManager.GetString("Login_SignIn", resourceCulture);
            }
        }
        
        public static string Login_SignInOAuth {
            get {
                return ResourceManager.GetString("Login_SignInOAuth", resourceCulture);
            }
        }
        
        public static string Login_WelcomeTo {
            get {
                return ResourceManager.GetString("Login_WelcomeTo", resourceCulture);
            }
        }
        
        public static string Main_Register {
            get {
                return ResourceManager.GetString("Main_Register", resourceCulture);
            }
        }
        
        public static string Welcome_SignIn {
            get {
                return ResourceManager.GetString("Welcome_SignIn", resourceCulture);
            }
        }
        
        public static string Welcome_SignUp {
            get {
                return ResourceManager.GetString("Welcome_SignUp", resourceCulture);
            }
        }
        
        public static string Activity_RegisterActivity {
            get {
                return ResourceManager.GetString("Activity_RegisterActivity", resourceCulture);
            }
        }
        
        public static string GLOBAL_NoInternetConnection {
            get {
                return ResourceManager.GetString("GLOBAL_NoInternetConnection", resourceCulture);
            }
        }
        
        public static string Main_Ends {
            get {
                return ResourceManager.GetString("Main_Ends", resourceCulture);
            }
        }
        
        public static string Main_LastDayWas {
            get {
                return ResourceManager.GetString("Main_LastDayWas", resourceCulture);
            }
        }
        
        public static string Main_LogOut {
            get {
                return ResourceManager.GetString("Main_LogOut", resourceCulture);
            }
        }
        
        public static string Main_Points {
            get {
                return ResourceManager.GetString("Main_Points", resourceCulture);
            }
        }
        
        public static string Main_Settings {
            get {
                return ResourceManager.GetString("Main_Settings", resourceCulture);
            }
        }
        
        public static string Main_StayInChallenge {
            get {
                return ResourceManager.GetString("Main_StayInChallenge", resourceCulture);
            }
        }
        
        public static string GLOBAL_Today {
            get {
                return ResourceManager.GetString("GLOBAL_Today", resourceCulture);
            }
        }
        
        public static string GLOBAL_Yesterday {
            get {
                return ResourceManager.GetString("GLOBAL_Yesterday", resourceCulture);
            }
        }
        
        public static string Main_You {
            get {
                return ResourceManager.GetString("Main_You", resourceCulture);
            }
        }
        
        public static string Activity_ShareToFacebook {
            get {
                return ResourceManager.GetString("Activity_ShareToFacebook", resourceCulture);
            }
        }
        
        public static string Activity_Cancel {
            get {
                return ResourceManager.GetString("Activity_Cancel", resourceCulture);
            }
        }
        
        public static string Activity_ChooseFromGallery {
            get {
                return ResourceManager.GetString("Activity_ChooseFromGallery", resourceCulture);
            }
        }
        
        public static string Activity_Comments {
            get {
                return ResourceManager.GetString("Activity_Comments", resourceCulture);
            }
        }
        
        public static string Activity_Distance {
            get {
                return ResourceManager.GetString("Activity_Distance", resourceCulture);
            }
        }
        
        public static string Activity_High {
            get {
                return ResourceManager.GetString("Activity_High", resourceCulture);
            }
        }
        
        public static string Activity_ImageChoosen {
            get {
                return ResourceManager.GetString("Activity_ImageChoosen", resourceCulture);
            }
        }
        
        public static string Activity_Intensity {
            get {
                return ResourceManager.GetString("Activity_Intensity", resourceCulture);
            }
        }
        
        public static string Activity_Low {
            get {
                return ResourceManager.GetString("Activity_Low", resourceCulture);
            }
        }
        
        public static string Activity_Minutes {
            get {
                return ResourceManager.GetString("Activity_Minutes", resourceCulture);
            }
        }
        
        public static string Activity_NoteLabel {
            get {
                return ResourceManager.GetString("Activity_NoteLabel", resourceCulture);
            }
        }
        
        public static string Activity_NoteText {
            get {
                return ResourceManager.GetString("Activity_NoteText", resourceCulture);
            }
        }
        
        public static string Activity_Save {
            get {
                return ResourceManager.GetString("Activity_Save", resourceCulture);
            }
        }
        
        public static string Activity_Steps {
            get {
                return ResourceManager.GetString("Activity_Steps", resourceCulture);
            }
        }
        
        public static string Activity_TakePhoto {
            get {
                return ResourceManager.GetString("Activity_TakePhoto", resourceCulture);
            }
        }
        
        public static string Activity_TrainingSaved {
            get {
                return ResourceManager.GetString("Activity_TrainingSaved", resourceCulture);
            }
        }
        
        public static string Activity_UploadAnyImage {
            get {
                return ResourceManager.GetString("Activity_UploadAnyImage", resourceCulture);
            }
        }
        
        public static string GLOBAL_Close {
            get {
                return ResourceManager.GetString("GLOBAL_Close", resourceCulture);
            }
        }
        
        public static string GLOBAL_Ok {
            get {
                return ResourceManager.GetString("GLOBAL_Ok", resourceCulture);
            }
        }
        
        public static string GLOBAL_Success {
            get {
                return ResourceManager.GetString("GLOBAL_Success", resourceCulture);
            }
        }
        
        public static string Main_NewsFeed_Activity1 {
            get {
                return ResourceManager.GetString("Main_NewsFeed_Activity1", resourceCulture);
            }
        }
        
        public static string Main_NewsFeed_Activity2 {
            get {
                return ResourceManager.GetString("Main_NewsFeed_Activity2", resourceCulture);
            }
        }
        
        public static string Main_NewsFeed_FORUMALL {
            get {
                return ResourceManager.GetString("Main_NewsFeed_FORUMALL", resourceCulture);
            }
        }
        
        public static string Main_NewsFeed_FORUMTEAM {
            get {
                return ResourceManager.GetString("Main_NewsFeed_FORUMTEAM", resourceCulture);
            }
        }
        
        public static string Main_NewsFeed_GOALSTREAM {
            get {
                return ResourceManager.GetString("Main_NewsFeed_GOALSTREAM", resourceCulture);
            }
        }
        
        public static string Main_NewsFeed_MEDAL {
            get {
                return ResourceManager.GetString("Main_NewsFeed_MEDAL", resourceCulture);
            }
        }
        
        public static string Main_NewsFeed_MEDALNEWS1 {
            get {
                return ResourceManager.GetString("Main_NewsFeed_MEDALNEWS1", resourceCulture);
            }
        }
        
        public static string Main_NewsFeed_MEDALNEWS2 {
            get {
                return ResourceManager.GetString("Main_NewsFeed_MEDALNEWS2", resourceCulture);
            }
        }
        
        public static string Main_NewsFeed_NEWS {
            get {
                return ResourceManager.GetString("Main_NewsFeed_NEWS", resourceCulture);
            }
        }
        
        public static string GLOBAL_ERROR_API_NeedUpdate {
            get {
                return ResourceManager.GetString("GLOBAL_ERROR_API_NeedUpdate", resourceCulture);
            }
        }
        
        public static string GLOBAL_ERROR_API_LOGIN_FunBeatUserNotFoundOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("GLOBAL_ERROR_API_LOGIN_FunBeatUserNotFoundOrPasswordIncorrect", resourceCulture);
            }
        }
        
        public static string GLOBAL_ERROR_API_SAVE_TRAINING_CouldNotPostToFacebook {
            get {
                return ResourceManager.GetString("GLOBAL_ERROR_API_SAVE_TRAINING_CouldNotPostToFacebook", resourceCulture);
            }
        }
        
        public static string GLOBAL_ERROR_API_SAVE_TRAINING_CouldNotSaveTraining {
            get {
                return ResourceManager.GetString("GLOBAL_ERROR_API_SAVE_TRAINING_CouldNotSaveTraining", resourceCulture);
            }
        }
        
        public static string GLOBAL_ERROR_API_SAVE_TRAINING_DailyLimitExceeded {
            get {
                return ResourceManager.GetString("GLOBAL_ERROR_API_SAVE_TRAINING_DailyLimitExceeded", resourceCulture);
            }
        }
        
        public static string GLOBAL_ERROR_API_SAVE_TRAINING_TrainingPersonIDCannotDifferFromLoggedInPersonID {
            get {
                return ResourceManager.GetString("GLOBAL_ERROR_API_SAVE_TRAINING_TrainingPersonIDCannotDifferFromLoggedInPersonID", resourceCulture);
            }
        }
        
        public static string Activity_NoteTextDayMax {
            get {
                return ResourceManager.GetString("Activity_NoteTextDayMax", resourceCulture);
            }
        }
        
        public static string Activity_NoteTextWeekMax {
            get {
                return ResourceManager.GetString("Activity_NoteTextWeekMax", resourceCulture);
            }
        }
        
        public static string GLOBAL_Exit_Dialog_Button_No {
            get {
                return ResourceManager.GetString("GLOBAL_Exit_Dialog_Button_No", resourceCulture);
            }
        }
        
        public static string GLOBAL_Exit_Dialog_Button_Yes {
            get {
                return ResourceManager.GetString("GLOBAL_Exit_Dialog_Button_Yes", resourceCulture);
            }
        }
        
        public static string GLOBAL_Exit_Dialog_Message {
            get {
                return ResourceManager.GetString("GLOBAL_Exit_Dialog_Message", resourceCulture);
            }
        }
        
        public static string GLOBAL_Exit_Dialog_Title {
            get {
                return ResourceManager.GetString("GLOBAL_Exit_Dialog_Title", resourceCulture);
            }
        }
        
        public static string Activity_Units_Fixed {
            get {
                return ResourceManager.GetString("Activity_Units_Fixed", resourceCulture);
            }
        }
        
        public static string Activity_Units_Minutes {
            get {
                return ResourceManager.GetString("Activity_Units_Minutes", resourceCulture);
            }
        }
        
        public static string Activity_Units_Score {
            get {
                return ResourceManager.GetString("Activity_Units_Score", resourceCulture);
            }
        }
        
        public static string Activity_Units_Steps {
            get {
                return ResourceManager.GetString("Activity_Units_Steps", resourceCulture);
            }
        }
        
        public static string Activity_EnterValidMinutes {
            get {
                return ResourceManager.GetString("Activity_EnterValidMinutes", resourceCulture);
            }
        }
        
        public static string Activity_EnterValidSteps {
            get {
                return ResourceManager.GetString("Activity_EnterValidSteps", resourceCulture);
            }
        }
        
        public static string Activity_SelectAtLeastOneDay {
            get {
                return ResourceManager.GetString("Activity_SelectAtLeastOneDay", resourceCulture);
            }
        }
        
        public static string Activity_AllTrainingsSaved {
            get {
                return ResourceManager.GetString("Activity_AllTrainingsSaved", resourceCulture);
            }
        }
        
        public static string Activity_SavedNotAllDays {
            get {
                return ResourceManager.GetString("Activity_SavedNotAllDays", resourceCulture);
            }
        }
        
        public static string Activity_TrainingCouldNotSave {
            get {
                return ResourceManager.GetString("Activity_TrainingCouldNotSave", resourceCulture);
            }
        }
        
        public static string Login_Splashtext {
            get {
                return ResourceManager.GetString("Login_Splashtext", resourceCulture);
            }
        }
        
        public static string Main_TryToRefresh {
            get {
                return ResourceManager.GetString("Main_TryToRefresh", resourceCulture);
            }
        }
        
        public static string Activity_TrainingLimitExceeded1Day {
            get {
                return ResourceManager.GetString("Activity_TrainingLimitExceeded1Day", resourceCulture);
            }
        }
        
        public static string Activity_TrainingLimitExceededAllDays {
            get {
                return ResourceManager.GetString("Activity_TrainingLimitExceededAllDays", resourceCulture);
            }
        }
        
        public static string Activity_LiveRecord {
            get {
                return ResourceManager.GetString("Activity_LiveRecord", resourceCulture);
            }
        }
        
        public static string Live_Record_Start {
            get {
                return ResourceManager.GetString("Live_Record_Start", resourceCulture);
            }
        }
        
        public static string Live_Record_Finish {
            get {
                return ResourceManager.GetString("Live_Record_Finish", resourceCulture);
            }
        }
        
        public static string Main_NoDetailInformation {
            get {
                return ResourceManager.GetString("Main_NoDetailInformation", resourceCulture);
            }
        }
        
        public static string Main_ReadOnSite {
            get {
                return ResourceManager.GetString("Main_ReadOnSite", resourceCulture);
            }
        }
        
        public static string Main_NewsDetail_FORUMALL {
            get {
                return ResourceManager.GetString("Main_NewsDetail_FORUMALL", resourceCulture);
            }
        }
        
        public static string Main_NewsDetail_FORUMTEAM {
            get {
                return ResourceManager.GetString("Main_NewsDetail_FORUMTEAM", resourceCulture);
            }
        }
        
        public static string Main_NewsFeed_MESSAGE {
            get {
                return ResourceManager.GetString("Main_NewsFeed_MESSAGE", resourceCulture);
            }
        }
        
        public static string Live_Record_Pause {
            get {
                return ResourceManager.GetString("Live_Record_Pause", resourceCulture);
            }
        }
        
        public static string Live_Record_Resume {
            get {
                return ResourceManager.GetString("Live_Record_Resume", resourceCulture);
            }
        }
        
        public static string Live_Record_Cancel {
            get {
                return ResourceManager.GetString("Live_Record_Cancel", resourceCulture);
            }
        }
        
        public static string Main_NewsFeed_PERSONALMESSAGE {
            get {
                return ResourceManager.GetString("Main_NewsFeed_PERSONALMESSAGE", resourceCulture);
            }
        }
        
        public static string LiveRecord_NoteLabel1 {
            get {
                return ResourceManager.GetString("LiveRecord_NoteLabel1", resourceCulture);
            }
        }
        
        public static string LiveRecord_NoteLabel2 {
            get {
                return ResourceManager.GetString("LiveRecord_NoteLabel2", resourceCulture);
            }
        }
        
        public static string GLOBAL_Restart {
            get {
                return ResourceManager.GetString("GLOBAL_Restart", resourceCulture);
            }
        }
        
        public static string Main_NewsFeedAll {
            get {
                return ResourceManager.GetString("Main_NewsFeedAll", resourceCulture);
            }
        }
        
        public static string Main_NewsFeedPersonal {
            get {
                return ResourceManager.GetString("Main_NewsFeedPersonal", resourceCulture);
            }
        }
        
        public static string MAIN_Restart_after_crash {
            get {
                return ResourceManager.GetString("MAIN_Restart_after_crash", resourceCulture);
            }
        }
        
        public static string GLOBAL_Confirm_Dialog_Title {
            get {
                return ResourceManager.GetString("GLOBAL_Confirm_Dialog_Title", resourceCulture);
            }
        }
        
        public static string LiveRecord_ConfirmExit {
            get {
                return ResourceManager.GetString("LiveRecord_ConfirmExit", resourceCulture);
            }
        }
        
        public static string BusyIndicatorContent {
            get {
                return ResourceManager.GetString("BusyIndicatorContent", resourceCulture);
            }
        }
        
        public static string ListPullToRefresh {
            get {
                return ResourceManager.GetString("ListPullToRefresh", resourceCulture);
            }
        }
        
        public static string ListPullToRefreshLoading {
            get {
                return ResourceManager.GetString("ListPullToRefreshLoading", resourceCulture);
            }
        }
        
        public static string ListPullToRefreshTime {
            get {
                return ResourceManager.GetString("ListPullToRefreshTime", resourceCulture);
            }
        }
        
        public static string ListReleaseToRefresh {
            get {
                return ResourceManager.GetString("ListReleaseToRefresh", resourceCulture);
            }
        }
        
        public static string GLOBAL_Server_not_available {
            get {
                return ResourceManager.GetString("GLOBAL_Server_not_available", resourceCulture);
            }
        }
        
        public static string Main_Close {
            get {
                return ResourceManager.GetString("Main_Close", resourceCulture);
            }
        }
        
        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        public static string Activity_PictureError {
            get {
                return ResourceManager.GetString("Activity_PictureError", resourceCulture);
            }
        }
        
        public static string Login_SplashtextAtea {
            get {
                return ResourceManager.GetString("Login_SplashtextAtea", resourceCulture);
            }
        }
        
        public static string Login_SplashtextNorden {
            get {
                return ResourceManager.GetString("Login_SplashtextNorden", resourceCulture);
            }
        }
        
        public static string Activity_RegisterFavotieActivity {
            get {
                return ResourceManager.GetString("Activity_RegisterFavotieActivity", resourceCulture);
            }
        }
        
        public static string Main_Favorit {
            get {
                return ResourceManager.GetString("Main_Favorit", resourceCulture);
            }
        }
        
        public static string Main_MyActivities {
            get {
                return ResourceManager.GetString("Main_MyActivities", resourceCulture);
            }
        }
    }
}
